name: Deployment of TripNJoy

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:

  install-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.1'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          architecture: x64
      - run: flutter pub get
      - run: flutter test

  install-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.1'
          channel: 'stable'
          architecture: 'x64'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      - run: flutter pub get
      - run: flutter test

  build-web:
    runs-on: ubuntu-latest
    needs: install-ubuntu
    steps:
      - run: flutter build web --dart-define=USER_POOL_ID=${{ secrets.USER_POOL_ID }} --dart-define=CLIENT_ID=${{ secrets.CLIENT_ID }} --dart-define=CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tripnjoy-web-app
          path: build/web/

  build-android:
    runs-on: ubuntu-latest
    needs: install-ubuntu
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: flutter build apk --dart-define=USER_POOL_ID=${{ secrets.USER_POOL_ID }} --dart-define=CLIENT_ID=${{ secrets.CLIENT_ID }} --dart-define=CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
      - run: flutter build appbundle --dart-define=USER_POOL_ID=${{ secrets.USER_POOL_ID }} --dart-define=CLIENT_ID=${{ secrets.CLIENT_ID }} --dart-define=CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tripnjoy-release-apk
          path: build/app/outputs/apk/release/app-release.apk

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.1'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          architecture: x64
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter test
      - run: flutter build windows --dart-define=USER_POOL_ID=${{ secrets.USER_POOL_ID }} --dart-define=CLIENT_ID=${{ secrets.CLIENT_ID }} --dart-define=CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tripnjoy-windows-exe
          path: build/windows/runner/Release/

  build-macos:
    runs-on: macos-latest
    needs: install-macos
    steps:
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos --dart-define=USER_POOL_ID=${{ secrets.USER_POOL_ID }} --dart-define=CLIENT_ID=${{ secrets.CLIENT_ID }} --dart-define=CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tripnjoy-macos-app
          path: build/macos/Build/Products/Release

  build-ios:
    runs-on: macos-latest
    needs: install-macos
    steps:
      - run: flutter build ios --release --no-codesign --dart-define=USER_POOL_ID=${{ secrets.USER_POOL_ID }} --dart-define=CLIENT_ID=${{ secrets.CLIENT_ID }} --dart-define=CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}

  release-macos:
    runs-on: macos-latest
    needs: build-macos
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - run: echo "::set-output name=version::$(grep -E 'version. (.*)' pubspec.yaml -m 1 > tmp && grep -Eo '\d.*' tmp && rm tmp)"
        name: Get version
        id: get_version
      - run: mkdir -p tmp/tripnjoy-macos-app && cd tmp/tripnjoy-macos-app
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: tripnjoy-macos-app
          path: /Users/runner/work/tripnjoy-macos-app/tripnjoy-macos-app/tmp
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.get_version.outputs.version }}
          tag_name: ${{ github.ref }}
          body: Some changes
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: chmod +x tripnjoy-macos-app.app/Contents/MacOS/tripnjoy-macos-app
      - run: cd /Users/runner/work/tripnjoy-macos-app/tripnjoy-macos-app/tmp && zip -r tripnjoy-macos-app.zip tripnjoy-macos-app
      - run: pwd
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /Users/runner/work/tripnjoy-macos-app/tripnjoy-macos-app/tripnjoy-macos-app.zip
          asset_name: tripnjoy-macos-app.zip
          asset_content_type: application/zip

  deploy-web:
    name: Deploy web
    needs: build-web
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

  release-all:
    needs: [build-android, build-windows]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - uses: ncipollo/release-action@v2
        with:
          artifacts: "artifacts/*.apk, artifacts/*.exe"
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}